name: Test Action

on:
  pull_request:

jobs:
  build-1:
    runs-on: ubuntu-latest
    steps:
      - name: Display PR body
        run: |
          echo "PR Body: ${{ github.event.pull_request.body }} 2"
          DEPLOY_ENV=$(echo "${{ github.event.pull_request.body }}" | grep "deploy_env:" | awk '{print $2}')
          echo "Deploy Env: $DEPLOY_ENV"


